[package]
name = "Circle-Bounce-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tinydraw = "0.1.1"
tempfile = "3.3.0"
